type CommandResponseVehicle {
  code: Int,
  message: String
}

type Query {
  "Get Vehicle membership time expiration"
  VehicleMembershipExpiration(licensePlate: String!): BigInt @requireAuth
}


type Mutation {
  "switch to subscription type mode. Using PAY_PER_SERVICE as default"
  VehicleMemberShipSwitchMode(licensePlate: String!, mode: String): CommandResponseVehicle @requireAuth
}